---
- hosts: drupal
  remote_user: username 
  become: yes
  roles:
    - role: users-role
    - role: nginx-role
      nginx_sites:
        drupal:
          template: drupal.conf.j2
          root: /home/drupaluser/drupal-site
          server_name: 192.168.1.3
        test:
          template: test_site.conf.j2
          server_name: drupal.local
    - role: mysql-role
    - role: php-role
      php_version: "7.0"
      php_packages:
        - php7.0-common
        - php7.0-intl
        - php7.0-cli
        - php7.0-dev
        - php7.0-fpm
        - php7.0-gd
        - php7.0-curl
        - php7.0-imap
        - php7.0-json
        - php7.0-opcache
        - php7.0-xml
        - php7.0-mbstring
        - php7.0-zip
        - php7.0-mysql
      php_date_timezone: "Europe/London"
      php_mysql_package: php7.0-mysql
    - role: drush-role
    - role: drupal-role
